[tool.poetry]
name = "poetry-env"
version = "0.1.0"
description = ""
authors = ["robson-morais <robson.starkp2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
